export const majorCities = [
  "Aachen",
  "Aalborg",
  "Aarhus",
  "Abidjan",
  "Abu Dhabi",
  "Abuja",
  "Accra",
  "Adana",
  "Addis Ababa",
  "Adelaide",
  "Agra",
  "Ahmedabad",
  "Aleppo",
  "Alexandria",
  "Algiers",
  "Almaty",
  "Amman",
  "Amsterdam",
  "Ankara",
  "Antalya",
  "Antwerp",
  "Auckland",
  "Austin",
  "Baghdad",
  "Baku",
  "Baltimore",
  "Bamako",
  "Bandung",
  "Bangalore",
  "Bangkok",
  "Barcelona",
  "Basel",
  "Beijing",
  "Beirut",
  "Belfast",
  "Belgrade",
  "Belo Horizonte",
  "Bengaluru",
  "Bergen",
  "Berlin",
  "Bern",
  "Bilbao",
  "Birmingham",
  "Bishkek",
  "Bogota",
  "Bologna",
  "Bonn",
  "Bordeaux",
  "Boston",
  "Brasilia",
  "Bratislava",
  "Braunschweig",
  "Bremen",
  "Bremerhaven",
  "Brisbane",
  "Bristol",
  "Brno",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Buenos Aires",
  "Cairo",
  "Calgary",
  "Canberra",
  "Cape Town",
  "Caracas",
  "Cardiff",
  "Casablanca",
  "Chengdu",
  "Chennai",
  "Chicago",
  "Chisinau",
  "Chongqing",
  "Christchurch",
  "Cologne",
  "Colombo",
  "Copenhagen",
  "Cordoba",
  "Curitiba",
  "Daegu",
  "Dakar",
  "Dallas",
  "Damascus",
  "Dar es Salaam",
  "Delhi",
  "Denver",
  "Detroit",
  "Dhaka",
  "Doha",
  "Dortmund",
  "Dresden",
  "Dubai",
  "Dublin",
  "Duisburg",
  "Dusseldorf",
  "Edinburgh",
  "Edmonton",
  "Eindhoven",
  "Essen",
  "Frankfurt",
  "Freiburg",
  "Fukuoka",
  "Gdansk",
  "Geneva",
  "Genoa",
  "Glasgow",
  "Gothenburg",
  "Graz",
  "Guangzhou",
  "Guatemala City",
  "Hamburg",
  "Hannover",
  "Hanoi",
  "Harare",
  "Havana",
  "Helsinki",
  "Ho Chi Minh City",
  "Hong Kong",
  "Houston",
  "Hyderabad",
  "Incheon",
  "Istanbul",
  "Jakarta",
  "Jeddah",
  "Jerusalem",
  "Johannesburg",
  "Kabul",
  "Kampala",
  "Karachi",
  "Kathmandu",
  "Khartoum",
  "Kiel",
  "Kigali",
  "Kinshasa",
  "Kolkata",
  "Kuala Lumpur",
  "Kyiv",
  "Kyoto",
  "Lagos",
  "Lahore",
  "Las Vegas",
  "Leeds",
  "Leipzig",
  "Lima",
  "Lisbon",
  "Liverpool",
  "Ljubljana",
  "London",
  "Los Angeles",
  "Lyon",
  "Madrid",
  "Manila",
  "Mannheim",
  "Marseille",
  "Melbourne",
  "Mexico City",
  "Miami",
  "Milan",
  "Minneapolis",
  "Minsk",
  "Monterrey",
  "Montreal",
  "Moscow",
  "Mumbai",
  "Munich",
  "Nairobi",
  "Naples",
  "New Delhi",
  "New York",
  "Nice",
  "Nuremberg",
  "Osaka",
  "Oslo",
  "Ottawa",
  "Paris",
  "Perth",
  "Philadelphia",
  "Phnom Penh",
  "Phoenix",
  "Portland",
  "Prague",
  "Quito",
  "Reykjavik",
  "Riga",
  "Rio de Janeiro",
  "Riyadh",
  "Rome",
  "Rotterdam",
  "San Diego",
  "San Francisco",
  "San Jose",
  "Santiago",
  "Sao Paulo",
  "Seattle",
  "Seoul",
  "Shanghai",
  "Shenzhen",
  "Singapore",
  "Sofia",
  "Stockholm",
  "Stuttgart",
  "Sydney",
  "Taipei",
  "Tallinn",
  "Tashkent",
  "Tbilisi",
  "Tehran",
  "Tel Aviv",
  "Tokyo",
  "Toronto",
  "Tunis",
  "Ulaanbaatar",
  "Valencia",
  "Vancouver",
  "Vienna",
  "Vilnius",
  "Warsaw",
  "Washington",
  "Wellington",
  "Winnipeg",
  "Wroclaw",
  "Yokohama",
  "Zagreb",
  "Akron",
  "Albany",
  "Albuquerque",
  "Allentown",
  "Anchorage",
  "Ann Arbor",
  "Appleton",
  "Aschaffenburg",
  "Asheville",
  "Aspen",
  "Atlanta",
  "Atlantic City",
  "Augsburg",
  "Aurora",
  "Baden-Baden",
  "Bakersfield",
  "Bamberg",
  "Bayreuth",
  "Beaverton",
  "Bellingham",
  "Bend",
  "Billings",
  "Bismarck",
  "Bloomington",
  "Boise",
  "Bozeman",
  "Bridgeport",
  "Buffalo",
  "Burbank",
  "Burlington",
  "Carlsbad",
  "Cedar Rapids",
  "Champaign",
  "Charleston",
  "Charlotte",
  "Charlottesville",
  "Chattanooga",
  "Chemnitz",
  "Cincinnati",
  "Cleveland",
  "Colorado Springs",
  "Columbia",
  "Columbus",
  "Corpus Christi",
  "Darmstadt",
  "Dayton",
  "Des Moines",
  "Dornbirn",
  "Erfurt",
  "Erlangen",
  "Eugene",
  "Evansville",
  "Fairbanks",
  "Fargo",
  "Fayetteville",
  "Flensburg",
  "Fort Lauderdale",
  "Fort Myers",
  "Fort Wayne",
  "Fort Worth",
  "Fresno",
  "Friedrichshafen",
  "Fürth",
  "Gainesville",
  "Gelsenkirchen",
  "Germering",
  "Giessen",
  "Grand Junction",
  "Grand Rapids",
  "Great Falls",
  "Greensboro",
  "Greenville",
  "Göttingen",
  "Hagen",
  "Halle",
  "Hampton",
  "Harrisburg",
  "Hartford",
  "Heidelberg",
  "Heilbronn",
  "Hildesheim",
  "Hollywood",
  "Huntsville",
  "Idaho Falls",
  "Ingolstadt",
  "Innsbruck",
  "Irvine",
  "Jackson",
  "Jacksonville",
  "Kaiserslautern",
  "Kansas City",
  "Karlsruhe",
  "Kassel",
  "Kempten",
  "Klagenfurt",
  "Koblenz",
  "Konstanz",
  "Krefeld",
  "Lech",
  "Linz",
  "Little Rock",
  "Long Beach",
  "Louisville",
  "Lubbock",
  "Lübeck",
  "Madison",
  "Magdeburg",
  "Mainz",
  "Memmingen",
  "Memphis",
  "Mesa",
  "Mobile",
  "Modesto",
  "Mönchengladbach",
  "Münster",
  "Myrtle Beach",
  "Nashville",
  "New Haven",
  "New Orleans",
  "Newark",
  "Newport News",
  "Norfolk",
  "Oberhausen",
  "Offenbach",
  "Oklahoma City",
  "Oldenburg",
  "Omaha",
  "Ontario",
  "Orange County",
  "Orlando",
  "Osnabrück",
  "Palm Springs",
  "Palo Alto",
  "Pasadena",
  "Pensacola",
  "Peoria",
  "Pittsburgh",
  "Potsdam",
  "Providence",
  "Raleigh",
  "Ravensburg",
  "Regensburg",
  "Reno",
  "Reutlingen",
  "Richmond",
  "Riverside",
  "Roanoke",
  "Rochester",
  "Rostock",
  "Sacramento",
  "Salt Lake City",
  "Salzburg",
  "San Antonio",
  "San Bernardino",
  "Santa Ana",
  "Santa Barbara",
  "Santa Clara",
  "Santa Rosa",
  "Savannah",
  "Schaumburg",
  "Schwerin",
  "Scottsdale",
  "Sioux Falls",
  "Spokane",
  "Springfield",
  "St. Gallen",
  "St. Louis",
  "St. Petersburg",
  "St. Pölten",
  "Stockton",
  "Syracuse",
  "Tacoma",
  "Tallahassee",
  "Tampa",
  "Toledo",
  "Tucson",
  "Tulsa",
  "Ulm",
  "Ventura",
  "Virginia Beach",
  "Waco",
  "Wichita",
  "Wiesbaden",
  "Winterthur",
  "Wolfsburg",
  "Wuppertal",
  "Würzburg",
  "Yonkers",
  "Zell am See",
  "Aalen",
  "Altenrhein",
  "Amstetten",
  "Ansbach",
  "Arlington",
  "Bad Homburg",
  "Bad Kreuznach",
  "Bad Reichenhall",
  "Baden",
  "Baden bei Wien",
  "Biberach",
  "Biel",
  "Bielefeld",
  "Bregenz",
  "Bruck an der Mur",
  "Brugg",
  "Böblingen",
  "Celle",
  "Chur",
  "Coburg",
  "Cottbus",
  "Davos",
  "Deggendorf",
  "Dessau",
  "Donaueschingen",
  "Dübendorf",
  "Düren",
  "Düsseldorf",
  "Eisenach",
  "Eisenstadt",
  "Emden",
  "Esslingen",
  "Feldkirch",
  "Fulda",
  "Garmisch-Partenkirchen",
  "Gera",
  "Grenchen",
  "Gütersloh",
  "Hahn",
  "Hof",
  "Klagenfurt am Wörthersee",
  "Kloten",
  "Krems",
  "Köln",
  "Landshut",
  "Lausanne",
  "Leoben",
  "Locarno",
  "Lugano",
  "Lüneburg",
  "Lünen",
  "Marburg",
  "Minden",
  "München",
  "Neubrandenburg",
  "Neumünster",
  "Neuss",
  "Passau",
  "Paderborn",
  "Pforzheim",
  "Plauen",
  "Rapperswil",
  "Remscheid",
  "Rosenheim",
  "Saarbrücken",
  "Schaffhausen",
  "Schwechat",
  "Schwäbisch Hall",
  "Siegen",
  "Sion",
  "Solingen",
  "Solothurn",
  "Speyer",
  "Steyr",
  "Thun",
  "Trier",
  "Tübingen",
  "Villach",
  "Villingen-Schwenningen",
  "Waidhofen",
  "Weeze",
  "Weimar",
  "Wels",
  "Westerland",
  "Wien",
  "Wiener Neustadt",
  "Wil",
  "Wilhelmshaven",
  "Winter Park",
  "Worms",
  "Zug",
  "Zwickau",
  "Zurich",
].sort((first, second) => first.localeCompare(second));
